/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadKindRouteImport } from './routes/upload.$kind'
import { Route as ResultsKindRouteImport } from './routes/results.$kind'
import { Route as ChatKindRouteImport } from './routes/chat.$kind'
import { Route as ChatKindIndexRouteImport } from './routes/chat.$kind.index'
import { Route as ChatKindThreadIdRouteImport } from './routes/chat.$kind.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadKindRoute = UploadKindRouteImport.update({
  id: '/upload/$kind',
  path: '/upload/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsKindRoute = ResultsKindRouteImport.update({
  id: '/results/$kind',
  path: '/results/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatKindRoute = ChatKindRouteImport.update({
  id: '/chat/$kind',
  path: '/chat/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatKindIndexRoute = ChatKindIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatKindRoute,
} as any)
const ChatKindThreadIdRoute = ChatKindThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatKindRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/$kind': typeof ChatKindRouteWithChildren
  '/results/$kind': typeof ResultsKindRoute
  '/upload/$kind': typeof UploadKindRoute
  '/chat/$kind/$threadId': typeof ChatKindThreadIdRoute
  '/chat/$kind/': typeof ChatKindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/results/$kind': typeof ResultsKindRoute
  '/upload/$kind': typeof UploadKindRoute
  '/chat/$kind/$threadId': typeof ChatKindThreadIdRoute
  '/chat/$kind': typeof ChatKindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/$kind': typeof ChatKindRouteWithChildren
  '/results/$kind': typeof ResultsKindRoute
  '/upload/$kind': typeof UploadKindRoute
  '/chat/$kind/$threadId': typeof ChatKindThreadIdRoute
  '/chat/$kind/': typeof ChatKindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat/$kind'
    | '/results/$kind'
    | '/upload/$kind'
    | '/chat/$kind/$threadId'
    | '/chat/$kind/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/results/$kind'
    | '/upload/$kind'
    | '/chat/$kind/$threadId'
    | '/chat/$kind'
  id:
    | '__root__'
    | '/'
    | '/chat/$kind'
    | '/results/$kind'
    | '/upload/$kind'
    | '/chat/$kind/$threadId'
    | '/chat/$kind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatKindRoute: typeof ChatKindRouteWithChildren
  ResultsKindRoute: typeof ResultsKindRoute
  UploadKindRoute: typeof UploadKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$kind': {
      id: '/upload/$kind'
      path: '/upload/$kind'
      fullPath: '/upload/$kind'
      preLoaderRoute: typeof UploadKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$kind': {
      id: '/results/$kind'
      path: '/results/$kind'
      fullPath: '/results/$kind'
      preLoaderRoute: typeof ResultsKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$kind': {
      id: '/chat/$kind'
      path: '/chat/$kind'
      fullPath: '/chat/$kind'
      preLoaderRoute: typeof ChatKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$kind/': {
      id: '/chat/$kind/'
      path: '/'
      fullPath: '/chat/$kind/'
      preLoaderRoute: typeof ChatKindIndexRouteImport
      parentRoute: typeof ChatKindRoute
    }
    '/chat/$kind/$threadId': {
      id: '/chat/$kind/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$kind/$threadId'
      preLoaderRoute: typeof ChatKindThreadIdRouteImport
      parentRoute: typeof ChatKindRoute
    }
  }
}

interface ChatKindRouteChildren {
  ChatKindThreadIdRoute: typeof ChatKindThreadIdRoute
  ChatKindIndexRoute: typeof ChatKindIndexRoute
}

const ChatKindRouteChildren: ChatKindRouteChildren = {
  ChatKindThreadIdRoute: ChatKindThreadIdRoute,
  ChatKindIndexRoute: ChatKindIndexRoute,
}

const ChatKindRouteWithChildren = ChatKindRoute._addFileChildren(
  ChatKindRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatKindRoute: ChatKindRouteWithChildren,
  ResultsKindRoute: ResultsKindRoute,
  UploadKindRoute: UploadKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
